name: fproject
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  html: ^0.14.0+3
  flutter_html: ^1.0.2
  carousel_slider: ^2.2.1  
  bloc: ^6.0.0
  pk_skeleton: ^0.0.2
  equatable: ^1.2.2
  rxdart: ^0.24.1
  shared_preferences: ^0.5.8
  curved_navigation_bar: ^0.3.3
  font_awesome_flutter: ^8.8.1
  file_picker: ^1.13.0+1
  dio: ^3.0.9
  flutter_staggered_grid_view: ^0.3.2
  photo_view: ^0.9.2
  flutter_downloader: ^1.4.4
  path_provider: ^1.6.11
  filesize: ^1.0.4
  emoji_picker: ^0.1.0
  socket_io: ^0.9.4
  permission_handler: 5.0.1+1
  fluttertoast: ^7.0.4
  double_back_to_close_app: ^1.2.0
  flutter_bloc: ^6.0.1
  pie_chart: 3.1.1
  flutter_circular_chart: ^0.1.0
  html_editor: ^1.0.1
  flutter_summernote: ^0.2.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  flutter_spinkit: ^4.1.2+1
  simple_animations: ^1.3.3
  percent_indicator: ^2.1.6
  socket_io_client: ^0.9.11
  flutter_socket_io: ^0.6.0
  toast: ^0.1.5
  webview_flutter: ^0.3.22+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/plan.jpg
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/font/Pacifico-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: CrimsonTextRegular
      fonts:
        - asset: assets/font/CrimsonText-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
